version: '3.4'

services:
  publicapigateway.host:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1qrG5!l19KrTav2
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx
      - GlobalConfiguration__BaseUrl=https://localhost:7000
      - GlobalConfiguration__ServiceDiscoveryProvider__Host=s_consul
      - GlobalConfiguration__ServiceDiscoveryProvider__Port=8500
      - GlobalConfiguration__ServiceDiscoveryProvider__Type=Consul
    ports:
      - "5000:80"
      - "7000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ./conf.d/https/:/https/

  managementmodule.webapi:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ServiceName: managementmodule.webapi
      ServicePort: 5010
      ConnectionStrings_ManagementModule: host=postgresql-master;Port=5432;Database=ManagementModuleDb;User Id=postgres;Password=postgres;CommandTimeout=300;
      Serilog__WriteTo__0__Args__collectionName: ManagementServiceLogs
    env_file:
      - env.files/from.consul.env
      - env.files/from.mongodb.env
      - env.files/from.rabbitmq.env
    ports:
      - "5010:80"

  userportalmodule.webapi:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ServiceName: userportalmodule.webapi
      ServicePort: 5020
      ConnectionStrings_UserPortalModule: host=postgresql-master;Port=5432;Database=UserPortalDb;User Id=postgres;Password=postgres;CommandTimeout=300;
      Serilog__WriteTo__0__Args__collectionName: UserPortalServiceLogs
    env_file:
      - env.files/from.consul.env
      - env.files/from.mongodb.env
      - env.files/from.rabbitmq.env
    ports:
      - "5020:80"

  managementmodule.eventprocessor:
    environment:
      ConnectionStrings_ManagementModule: host=postgresql-master;Port=5432;Database=ManagementModuleDb;User Id=postgres;Password=postgres;CommandTimeout=300;
      Serilog__WriteTo__0__Args__collectionName: ManagementEventLogs
    env_file:
      - env.files/from.mongodb.env
      - env.files/from.rabbitmq.env

  userportalmodule.eventprocessor:
    environment:
      ConnectionStrings_UserPortalModule: host=postgresql-master;Port=5432;Database=UserPortalDb;User Id=postgres;Password=postgres;CommandTimeout=300;
      Serilog__WriteTo__0__Args__collectionName: UserPortalEventLogs
    env_file:
      - env.files/from.mongodb.env
      - env.files/from.rabbitmq.env
      
  postgresql-master:
    env_file:
      - env.files/postgresql-master.env
    ports:
      - '5432:5432'

  postgresql-slave-1:
    env_file:
      - env.files/postgresql-slave.env
    ports:
      - '5432'
    depends_on:
      - postgresql-master

  postgresql-slave-2:
    env_file:
      - env.files/postgresql-slave.env
    ports:
      - '5432'
    depends_on:
      - postgresql-master

  postgresql-slave-3:
    env_file:
      - env.files/postgresql-slave.env
    ports:
      - '5432'
    depends_on:
      - postgresql-master

  postgresql-slave-4:
    env_file:
      - env.files/postgresql-slave.env
    ports:
      - '5432'
    depends_on:
      - postgresql-master

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '${PGADMIN_PORT:-5050}:80'

  s_consul:
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp

  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_VHOST=mbs
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
        - 5672:5672
        - 15672:15672
