version: '3.4'

services:
  publicapigateway.host:
    image: ${DOCKER_REGISTRY-}publicapigatewayhost
    build:
      context: .
      dockerfile: src/Gateways/PublicApiGateway.Host/Dockerfile
    depends_on:
      - "mongo"
      - "postgresql-master"
      - "managementmodule.replica1.webapi"
      - "managementmodule.replica2.webapi"
      - "userportalmodule.replica1.webapi"
      - "userportalmodule.replica2.webapi"
      - "userportalmodule.replica3.webapi"
    networks:
      - blogsite-network

  managementmodule.replica1.webapi:
    image: ${DOCKER_REGISTRY-}managementmodulewebapi
    build:
      context: .
      dockerfile: src/ManagementModule/ManagementModule.WebApi/Dockerfile
    depends_on:
      - "mongo"
      - "postgresql-master"
      - "s_consul"
      - "rabbitmq"
    networks:
      - blogsite-network

  managementmodule.replica2.webapi:
    image: ${DOCKER_REGISTRY-}managementmodulewebapi
    build:
      context: .
      dockerfile: src/ManagementModule/ManagementModule.WebApi/Dockerfile
    depends_on:
      - "mongo"
      - "postgresql-master"
      - "s_consul"
      - "rabbitmq"
      - "managementmodule.replica1.webapi"
    networks:
      - blogsite-network

  userportalmodule.replica1.webapi:
    image: ${DOCKER_REGISTRY-}userportalmodulewebapi
    build:
      context: .
      dockerfile: src/UserPortalModule/UserPortalModule.WebApi/Dockerfile
    depends_on:
      - "mongo"
      - "postgresql-master"
      - "s_consul"
      - "rabbitmq"
    networks:
      - blogsite-network

  userportalmodule.replica2.webapi:
    image: ${DOCKER_REGISTRY-}userportalmodulewebapi
    build:
      context: .
      dockerfile: src/UserPortalModule/UserPortalModule.WebApi/Dockerfile
    depends_on:
      - "mongo"
      - "postgresql-master"
      - "s_consul"
      - "rabbitmq"
      - "userportalmodule.replica1.webapi"
    networks:
      - blogsite-network

  userportalmodule.replica3.webapi:
    image: ${DOCKER_REGISTRY-}userportalmodulewebapi
    build:
      context: .
      dockerfile: src/UserPortalModule/UserPortalModule.WebApi/Dockerfile
    depends_on:
      - "mongo"
      - "postgresql-master"
      - "s_consul"
      - "rabbitmq"
      - "userportalmodule.replica1.webapi"
      - "userportalmodule.replica2.webapi"
    networks:
      - blogsite-network

  managementmodule.eventprocessor:
    image: ${DOCKER_REGISTRY-}managementmoduleeventprocessor
    build:
      context: .
      dockerfile: src/ManagementModule/ManagementModule.EventProcessor/Dockerfile
    depends_on:
      - "mongo"
      - "postgresql-master"
      - "rabbitmq"
    networks:
      - blogsite-network

  userportalmodule.eventprocessor:
    image: ${DOCKER_REGISTRY-}userportalmoduleeventprocessor
    build:
      context: .
      dockerfile: src/UserPortalModule/UserPortalModule.EventProcessor/Dockerfile
    depends_on:
      - "mongo"
      - "postgresql-master"
      - "rabbitmq"
    networks:
      - blogsite-network

  postgresql-master:
    image: docker.io/bitnami/postgresql:14
    volumes:
      - 'vol_app_master_db:/bitnami/postgresql'
    networks:
      - blogsite-network

  postgresql-slave-1:
    image: docker.io/bitnami/postgresql:14
    volumes:
      - 'vol_app_slave_1_db:/bitnami/postgresql'
    depends_on:
      - "postgresql-master"
    networks:
      - blogsite-network

  postgresql-slave-2:
    image: docker.io/bitnami/postgresql:14
    volumes:
      - 'vol_app_slave_2_db:/bitnami/postgresql'
    depends_on:
      - "postgresql-master"
      - "postgresql-slave-1"
    networks:
      - blogsite-network

  postgresql-slave-3:
    image: docker.io/bitnami/postgresql:14
    volumes:
      - 'vol_app_slave_3_db:/bitnami/postgresql'
    depends_on:
      - "postgresql-master"
      - "postgresql-slave-1"
      - "postgresql-slave-2"
    networks:
      - blogsite-network

  postgresql-slave-4:
    image: docker.io/bitnami/postgresql:14
    volumes:
      - 'vol_app_slave_4_db:/bitnami/postgresql'
    depends_on:
      - "postgresql-master"
      - "postgresql-slave-1"
      - "postgresql-slave-2"
      - "postgresql-slave-3"
    networks:
      - blogsite-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    volumes:
      - 'vol_pgadmin:/var/lib/pgadmin'
    restart: unless-stopped
    networks:
      - blogsite-network

  s_consul:
    container_name: c_consul
    image: consul
    networks:
      - blogsite-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_VHOST=mbs
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    volumes:
        - vol_rabbitmq_data:/var/lib/rabbitmq/
        - vol_rabbitmq_log:/var/log/rabbitmq
    networks:
      - blogsite-network

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - blogsite-network

  mongoexpress:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
    networks:
      - blogsite-network

volumes:
  vol_rabbitmq_data:
  vol_rabbitmq_log:
  vol_app_master_db:
  vol_app_slave_1_db:
  vol_app_slave_2_db:
  vol_app_slave_3_db:
  vol_app_slave_4_db:
  vol_pgadmin:

networks:
  blogsite-network:
    driver: bridge
