version: '3.4'

services:
  publicapigateway.host:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1qrG5!l19KrTav2
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx
      - Serilog__WriteTo__0__Args__collectionName=ApiGatewayLogs
      - GlobalConfiguration__ServiceDiscoveryProvider__Host=s_consul
      - Routes__0__DownstreamHostAndPorts__0__Host=managementmodule.replica1.webapi
      - Routes__0__DownstreamHostAndPorts__0__Port=5010
      - Routes__0__DownstreamHostAndPorts__1__Host=managementmodule.replica2.webapi
      - Routes__0__DownstreamHostAndPorts__1__Port=5011
      - Routes__1__DownstreamHostAndPorts__0__Host=userportalmodule.replica1.webapi
      - Routes__1__DownstreamHostAndPorts__0__Port=5020
      - Routes__1__DownstreamHostAndPorts__1__Host=userportalmodule.replica2.webapi
      - Routes__1__DownstreamHostAndPorts__1__Port=5021
      - Routes__1__DownstreamHostAndPorts__2__Host=userportalmodule.replica3.webapi
      - Routes__1__DownstreamHostAndPorts__2__Port=5022
    ports:
      - "5000:80"
      - "7000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ./conf.d/https/:/https/
    env_file:
      - env.files/from.mongodb.env

  managementmodule.replica1.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5010
      - ServiceName=managementmodule.replica1.webapi
      - ServicePort=5010
      - SystemOptions__SeedSampleData=true
      - ConnectionStrings__ManagementModule=host=postgresql-master;Port=5432;Database=ManagementModuleDb;User Id=postgres;Password=postgres;CommandTimeout=300;
      - Serilog__WriteTo__0__Args__collectionName=ManagementServiceLogs
    env_file:
      - env.files/from.auth.env
      - env.files/from.consul.env
      - env.files/from.mongodb.env
      - env.files/from.rabbitmq.env
    ports:
      - "5010:5010"

  managementmodule.replica2.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5011
      - ServiceName=managementmodule.replica2.webapi
      - ServicePort=5011
      - SystemOptions__SeedSampleData=false
      - ConnectionStrings__ManagementModule=host=postgresql-master;Port=5432;Database=ManagementModuleDb;User Id=postgres;Password=postgres;CommandTimeout=300;
      - Serilog__WriteTo__0__Args__collectionName=ManagementServiceLogs
    env_file:
      - env.files/from.auth.env
      - env.files/from.consul.env
      - env.files/from.mongodb.env
      - env.files/from.rabbitmq.env
    ports:
      - "5011:5011"

  userportalmodule.replica1.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5020
      - ServiceName=userportalmodule.replica1.webapi
      - ServicePort=5020
      - SystemOptions__SeedSampleData=true
      - ConnectionStrings__UserPortalModule=host=postgresql-master;Port=5432;Database=ManagementModuleDb;User Id=postgres;Password=postgres;CommandTimeout=300;
      - Serilog__WriteTo__0__Args__collectionName=UserPortalServiceLogs
    env_file:
      - env.files/from.consul.env
      - env.files/from.mongodb.env
      - env.files/from.rabbitmq.env
    ports:
      - "5020:5020"

  userportalmodule.replica2.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5021
      - ServiceName=userportalmodule.replica2.webapi
      - ServicePort=5021
      - SystemOptions__SeedSampleData=false
      - ConnectionStrings__UserPortalModule=host=postgresql-master;Port=5432;Database=ManagementModuleDb;User Id=postgres;Password=postgres;CommandTimeout=300;
      - Serilog__WriteTo__0__Args__collectionName=UserPortalServiceLogs
    env_file:
      - env.files/from.consul.env
      - env.files/from.mongodb.env
      - env.files/from.rabbitmq.env
    ports:
      - "5021:5021"

  userportalmodule.replica3.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5022
      - ServiceName=userportalmodule.replica3.webapi
      - ServicePort=5022
      - SystemOptions__SeedSampleData=false
      - ConnectionStrings__UserPortalModule=host=postgresql-master;Port=5432;Database=ManagementModuleDb;User Id=postgres;Password=postgres;CommandTimeout=300;
      - Serilog__WriteTo__0__Args__collectionName=UserPortalServiceLogs
    env_file:
      - env.files/from.consul.env
      - env.files/from.mongodb.env
      - env.files/from.rabbitmq.env
    ports:
      - "5022:5022"

  managementmodule.eventprocessor:
    environment:
      - ConnectionStrings__ManagementModule=host=postgresql-master;Port=5432;Database=ManagementModuleDb;User Id=postgres;Password=postgres;CommandTimeout=300;
      - Serilog__WriteTo__0__Args__collectionName=ManagementEventLogs
    env_file:
      - env.files/from.mongodb.env
      - env.files/from.rabbitmq.env

  userportalmodule.eventprocessor:
    environment:
      - ConnectionStrings__UserPortalModule=host=postgresql-master;Port=5432;Database=UserPortalDb;User Id=postgres;Password=postgres;CommandTimeout=300;
      - Serilog__WriteTo__0__Args__collectionName=UserPortalEventLogs
    env_file:
      - env.files/from.mongodb.env
      - env.files/from.rabbitmq.env
      
  postgresql-master:
    env_file:
      - env.files/postgresql-master.env
    ports:
      - '5432:5432'

  postgresql-slave-1:
    env_file:
      - env.files/postgresql-slave.env
    ports:
      - '5432'
    depends_on:
      - postgresql-master

  postgresql-slave-2:
    env_file:
      - env.files/postgresql-slave.env
    ports:
      - '5432'
    depends_on:
      - postgresql-master

  postgresql-slave-3:
    env_file:
      - env.files/postgresql-slave.env
    ports:
      - '5432'
    depends_on:
      - postgresql-master

  postgresql-slave-4:
    env_file:
      - env.files/postgresql-slave.env
    ports:
      - '5432'
    depends_on:
      - postgresql-master

  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-postgres}
      - PGADMIN_CONFIG_SERVER_MODE='False'
    ports:
      - '${PGADMIN_PORT:-5050}:80'

  s_consul:
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp

  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_VHOST=mbs
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
        - 5672:5672
        - 15672:15672
